### ISSUE TITLE
Błąd przy uruchomieniu.

### ISSUE THREAD

**Issue by mrto** [bohdanbobrowski/pr-dl#2]
```
Traceback (most recent call last):
  File "/home/mrto/.local/bin/prdl", line 11, in <module>
    load_entry_point('pr-dl==0.4', 'console_scripts', 'prdl')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/mrto/.local/lib/python2.7/site-packages/prdl/prdlcli.py", line 4, in <module>
    from prdl import PrDlCrawl, PrDlSearch
  File "/home/mrto/.local/lib/python2.7/site-packages/prdl/prdl.py", line 5, in <module>
    import eyed3
  File "/home/mrto/.local/lib/python2.7/site-packages/eyed3/__init__.py", line 30, in <module>
    from .utils.log import log                                          # noqa: E402
  File "/home/mrto/.local/lib/python2.7/site-packages/eyed3/utils/__init__.py", line 361
    msg = f"invalid level choice: {level} (choose from {parser.log_levels})"
                                                                           ^
SyntaxError: invalid syntax
```

**Comment by bohdanbobrowski** [comment]
This issue is not related to my script but to eyed3 library, which doesn't work in it's latest version on Python 2.7. Try to reinstall eyed3 by entering:
```
pip uninstall eyed3
pip install eyed3==0.8.12
```
...or just reinstll my script, I've added tiny fix for that.

Regards.
B.
