### ISSUE TITLE
Lame tag CRC check failed

### ISSUE THREAD

**Issue by bohdanbobrowski** [bohdanbobrowski/pr-dl#4]
prdl "Wańkowicz" -f

```
Successfully downloaded file to ./eugeniusz-kwiatkowski-melchior-wankowicz-premiera-w-teatrze-telewizji.mp3
Lame tag CRC check failed
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/PIL/Image.py", line 2152, in save
    format = EXTENSION[ext]
KeyError: '.jpg?format=500'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/bohdan/.local/bin/prdl", line 8, in <module>
    sys.exit(main())
  File "/home/bohdan/.local/lib/python3.9/site-packages/prdl/prdlcli.py", line 44, in main
    prdl.start()
  File "/home/bohdan/.local/lib/python3.9/site-packages/prdl/prdl.py", line 252, in start
    self.downloadPodcastsList(podcasts)
  File "/home/bohdan/.local/lib/python3.9/site-packages/prdl/prdl.py", line 245, in downloadPodcastsList
    self.downloadPodcast(podcasts[k], a, len(podcasts))
  File "/home/bohdan/.local/lib/python3.9/site-packages/prdl/prdl.py", line 211, in downloadPodcast
    podcast.downloadThumbnail()
  File "/home/bohdan/.local/lib/python3.9/site-packages/prdl/prdl.py", line 103, in downloadThumbnail
    background.save(self.thumbnail_file_name)
  File "/usr/lib/python3.9/site-packages/PIL/Image.py", line 2154, in save
    raise ValueError(f"unknown file extension: {ext}") from e
ValueError: unknown file extension: .jpg?format=500
```

**Comment by bohdanbobrowski** [comment]
Issue still occurs,however it's catched and it does not interrupt download process.
